### ISSUE TITLE
Get error when no alerts are available

### ISSUE THREAD

**Issue by haromatsu** [carbonblack/cbc-syslog#29]
I get following error when no alerts are available on the backend server.
If alerts were available, finishes without errors.

# cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)
# rpm -qa | grep cb-defense
python-cb-defense-syslog-1.2-12.x86_64
#
# tail -12 /var/log/cb/integrations/cb-defense-syslog/cb-defense-syslog.log
2019-04-08 09:00:02,631 - __main__ - INFO - Number of files in store forward: 0
2019-04-08 09:00:02,631 - __main__ - INFO - Found 1 Cb Defense Servers in config file
2019-04-08 09:00:02,631 - __main__ - INFO - Handling notifications for https://api-prod05.conferdeploy.net
2019-04-08 09:00:02,631 - __main__ - INFO - Attempting to connect to url: https://api-prod05.conferdeploy.net
2019-04-08 09:00:03,330 - __main__ - INFO - <Response [200]>
2019-04-08 09:00:03,330 - __main__ - INFO - successfully connected, no alerts at this time
2019-04-08 09:00:03,330 - __main__ - INFO - There are no messages to forward to host
2019-04-08 09:00:03,330 - __main__ - ERROR - 'NoneType' object is not iterable
Traceback (most recent call last):
  File "cb_defense_syslog.py", line 740, in <module>
  File "cb_defense_syslog.py", line 675, in main
TypeError: 'NoneType' object is not iterable

**Comment by smultani** [comment]
Hello haromatsu,

Can you uninstall cleanly by doing:
```
- rpm -e python-cb-defense-syslog
- rm -rf /usr/share/cb/integrations/cb-defense-syslog/
- rm -rf /var/log/cb/integrations/cb-defense-syslog/
- rm -rf /etc/cb/integrations/cb-defense-syslog/
```
install it again:

```
yum install python-cb-defense-syslog
```

We are not seeing any this error on our side. 

Thanks!

**Comment by avanbrunt-cb** [comment]
No response
