### ISSUE TITLE
[ERROR] LEEF output format

### ISSUE THREAD

**Issue by Lu-Ka** [carbonblack/cbc-syslog#36]
Hello team,

It seems the LEEF output format is a little bit broken..

It's weird because in your config file you don't mention the possibility to put this kind of output : **"Output format of the data sent. Currently support json or cef formats"**.
But when we read the python file, there is this possibility : **"logger.error('Must specify JSON, CEF , or LEEF output format')"** (line 162)

### OS version
> Red Hat Enterprise Linux Server release 7.7 (Maipo)

### Package version
> python-cb-defense-syslog-1.2-12.x86_64

### Log error
```
2020-01-02 17:15:21,634 - __main__ - INFO - Handling notifications for https://api-prod0X.conferdeploy.net
2020-01-02 17:15:21,635 - __main__ - INFO - Attempting to connect to url: https://api-prod0X.conferdeploy.net
2020-01-02 17:15:21,786 - __main__ - INFO - <Response [200]>
2020-01-02 17:15:21,787 - __main__ - ERROR - 'dict' object has no attribute 'json'
Traceback (most recent call last):
  File "cb_defense_syslog.py", line 740, in <module>
  File "cb_defense_syslog.py", line 657, in main
  File "cb_defense_syslog.py", line 78, in parse_cb_defense_response_leef
AttributeError: 'dict' object has no attribute 'json'
```

We would like to use this connector to forward Carbon Black Defense logs to our Qradar instance. This last requires the logs in LEEF format to works properly..

Thank you in advance for your help on this case !

Regards,

Lucas A.

**Comment by avanbrunt-cb** [comment]
Template support will replace out of the box LEEF and CEF formats to enable more control over what gets sent and in where. This will be included in CBC Syslog 2.0
