### ISSUE TITLE
OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by tsukasai-vmw** [carbonblack/cbc-syslog#82]
### Describe the bug

In the Windows OS environment, the scripts (core.py, output.py etc) will result in the following error when attempting to use unsupported characters (":") in a file name on Windows.

---
2023-12-06 11:17:38,983 - cbc_syslog.cli - ERROR - [Errno 22] Invalid argument: 'C:\\cbc-syslog2\\backup\\cbc-2023-12-06T11:16:08.436704Z.bck'
Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\site-packages\cbc_syslog\cli.py", line 115, in main
    succeeded = poll(Config(args.config_file))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\cbc_syslog\core.py", line 149, in poll
    with open(backup_file, "a") as backup:
         ^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: 'C:\\cbc-syslog2\\backup\\cbc-2023-12-06T11:16:08.436704Z.bck'

### Reproduction steps

It always reproduces in the Windows environment.

### Expected behavior

Use file names supported by Windows.

**Comment by avanbrunt-cb** [comment]
@tsukasai-vmw This has been fixed with 2.0.2 release
